### PR TITLE
Added Onedark Themed wallpaper

### PR DESCRIPTION
**Pull request by Mangeshrex**
Added void onedark wallpaper

### CODE REVIEW

**Comment by siduck76** [comment]
@Mangeshrex nice wallpaper  buddy , can you remove these strips? 
image

**Comment by Mangeshrex** [comment]
-__- i used my xresources for that itself but if you want ill remove em.

**Comment by Mangeshrex** [comment]
> -__- i used my xresources for that itself but if you want ill remove em.

But that was looking good duck

**Comment by siduck76** [comment]
> > -__- i used my xresources for that itself but if you want ill remove em.
> 
> But that was looking good duck

yes it looks nice but fat af :/

**Comment by Mangeshrex** [comment]
> > > -__- i used my xresources for that itself but if you want ill remove em.
> > 
> > 
> > But that was looking good duck
> 
> yes it looks nice but fat af :/

oki ill try making them lean

**Comment by siduck76** [comment]
> > > > -__- i used my xresources for that itself but if you want ill remove em.
> > > 
> > > 
> > > But that was looking good duck
> > 
> > 
> > yes it looks nice but fat af :/
> 
> oki ill try making them lean

you made that wall?

**Comment by Mangeshrex** [comment]
wall
see

**Comment by siduck76** [comment]
@Mangeshrex remove the corner strips , i bet it'll look more sexy.

**Comment by Mangeshrex** [comment]
> @Mangeshrex remove the corner strips , i bet it'll look more sexy.

ok senpai ill do and after that i have to change the file in my repo right? this was my first pr so asking

**Comment by Mangeshrex** [comment]
VOID LINUX
you are sure?

**Comment by siduck76** [comment]
@Mangeshrex very nice, send a PR for this too

**Comment by siduck76** [comment]
check this :))

https://github.com/vcyzteen/dotbaka

**Comment by Mangeshrex** [comment]
That looks very sexy

**Comment by Mangeshrex** [comment]
> @Mangeshrex very nice, send a PR for this too

both or only this one?

**Comment by siduck76** [comment]
> > @Mangeshrex very nice, send a PR for this too
> 
> both or only this one?

I merged previous wallpaper , send this wall in next PR

**Comment by Mangeshrex** [comment]
ok

**Pull request merged**
